name: CI/CD for FastAPI Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: [your-runner-tag]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt                

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest --disable-warnings                

  build-and-push-docker:
    runs-on: [your-runner-tag]
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t alisalsali/fast_api:latest .

    - name: Push Docker image to Docker Hub
      run: docker push alisalsali/fast_api:latest
